/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Calculadora;

/**
 *
 * @author Yeri
 */
public class PnlCalculadora extends javax.swing.JPanel {

    public float primeroNumero;
    public float segundoNumero;
    public String operador;

    public PnlCalculadora() {
        initComponents();
        //this.setLocationRelativeTo(null);//Aparece pantalla al centro cuando se compila
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        lblCasilla = new javax.swing.JLabel();
        btnDiv = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(490, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(0, 102, 102));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 65, 60));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 102, 102));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 65, 60));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(0, 102, 102));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 65, 60));

        btnIgual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(0, 153, 255));
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 65, 130));

        btn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(0, 102, 102));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 65, 60));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(0, 102, 102));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 65, 60));

        btnPunto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(0, 153, 0));
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 65, 60));

        btnSuma.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(0, 153, 0));
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 65, 130));

        btn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(0, 102, 102));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 144, 60));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(0, 102, 102));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 65, 60));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(0, 102, 102));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 65, 60));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(0, 102, 102));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 65, 60));

        btnResta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnResta.setForeground(new java.awt.Color(0, 153, 0));
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 65, 60));

        lblCasilla.setBackground(new java.awt.Color(255, 255, 255));
        lblCasilla.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblCasilla.setForeground(new java.awt.Color(102, 51, 0));
        lblCasilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCasilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        lblCasilla.setOpaque(true);
        add(lblCasilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 60));

        btnDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(0, 153, 0));
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 65, 60));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 102, 102));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 65, 60));

        btnMult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMult.setForeground(new java.awt.Color(0, 153, 0));
        btnMult.setText("*");
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        add(btnMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 65, 60));

        btnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 0, 0));
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 65, 60));

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/iconoCompras.gif"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 150));

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/3.jpg"))); // NOI18N
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 150, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        this.segundoNumero = Float.parseFloat(this.lblCasilla.getText());

        switch (this.operador) {
            case "+":
                this.lblCasilla.setText(sinCero(this.primeroNumero + this.segundoNumero));//sinCero va a transformar para quitar los .0
                break;
            case "-":
                this.lblCasilla.setText(sinCero(this.primeroNumero - this.segundoNumero));
                break;
            case "*":
                this.lblCasilla.setText(sinCero(this.primeroNumero * this.segundoNumero));
                break;
            case "/":
                if (this.segundoNumero == 0) {
                    this.lblCasilla.setText("No se divide entre cero");
                } else {//this.lblCasilla.setText(Float.toString(this.primeroNumero / this.segundoNumero));

                    this.lblCasilla.setText(sinCero(this.primeroNumero / this.segundoNumero));
                }
                break;
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (!(this.lblCasilla.getText().contains("."))) {
            this.lblCasilla.setText(this.lblCasilla.getText() + ".");
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        this.primeroNumero = Float.parseFloat(this.lblCasilla.getText());
        this.operador = "+";
        this.lblCasilla.setText("");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "0"); //Get es para capturar, Set para asignar
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        this.primeroNumero = Float.parseFloat(this.lblCasilla.getText());
        this.operador = "-";
        this.lblCasilla.setText("");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        this.primeroNumero = Float.parseFloat(this.lblCasilla.getText());
        this.operador = "/";
        this.lblCasilla.setText("");
    }//GEN-LAST:event_btnDivActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.lblCasilla.setText(this.lblCasilla.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        this.primeroNumero = Float.parseFloat(this.lblCasilla.getText());
        this.operador = "*";
        this.lblCasilla.setText("");
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        this.lblCasilla.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    public String sinCero(float resultado) {
        String retorno = "";
        retorno = Float.toString(resultado);

        if (resultado % 1 == 0) {
            retorno = retorno.substring(0, retorno.length() - 2);
        }
        return retorno;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblCasilla;
    // End of variables declaration//GEN-END:variables
}
