/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Fibonacci;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Yeri
 */
public class PnlFibonacci extends javax.swing.JPanel {

    /**
     * Creates new form PnlFibonacci
     */
    public PnlFibonacci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnAceptar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 0, 102));
        setMinimumSize(new java.awt.Dimension(490, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("***** FIBONACCI *****");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 153));
        jLabel3.setText("Ingrese extensión de la serie:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 220, 20));

        txtLimite.setEditable(false);
        txtLimite.setBackground(new java.awt.Color(255, 255, 153));
        txtLimite.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        txtLimite.setForeground(new java.awt.Color(153, 0, 51));
        txtLimite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 50, 30));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(153, 255, 204));
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(153, 0, 102));
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 360, 180));

        btnAceptar.setBackground(new java.awt.Color(255, 153, 51));
        btnAceptar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 102, 102));
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 100, 30));

        btnNuevo.setBackground(new java.awt.Color(102, 255, 102));
        btnNuevo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 102, 102));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 110, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/f2.gif"))); // NOI18N
        jLabel1.setToolTipText("Ingrese valores numéricos");
        jLabel1.setPreferredSize(new java.awt.Dimension(490, 490));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 420));
    }// </editor-fold>//GEN-END:initComponents
/* //LO PONEMOS CO COMENTARIO PORQUE ELIMINAMOS EL BOTON SALIR DEL JPANEL*/
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            int a = 1, b = 0, c = 0, n, limite = 0;
            n = Integer.parseInt(txtLimite.getText());

            do {
                a = a + b;
                b = c;
                c = a;
                limite++;

            } while (a <= n);
            a = 1;
            b = 0;
            c = 0;
            for (int i = 1; i <= limite; i++) {
                a = a + b;
                b = c;
                c = a;

                if (i < limite) {
                    txtResultado.append(c + "   ");
                }
            }
            habilitaControles(false);
        } catch (Exception e) {
            Component rootPane = null;
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitaControles(true);
        limpiaControles(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void habilitaControles(boolean b) {
        txtLimite.setEditable(b);
        txtResultado.setEditable(b);
        btnAceptar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        txtLimite.grabFocus();

    }

    private void limpiaControles(boolean par) {
        txtResultado.setText(null);
        txtLimite.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
